name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.2.4
homepage: https://github.com/brianegan/chewie

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  provider: ^5.0.0
  wakelock: ^0.5.2
  ext_video_player: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
